CREATE TABLE IF NOT EXISTS users_otp (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    userId VARCHAR(100) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expireAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);